---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    name: aws-ecr-proxy
  name: aws-ecr-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-ecr-proxy
  template:
    metadata:
      labels:
        name:  aws-ecr-proxy
    spec:
      containers:
      - name: aws-ecr-proxy
        image: catalinpan/aws-ecr-proxy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        - containerPort: 443
          protocol: TCP
          name: https
        env:
          - name: AWS_KEY
            value: 'YOUR_AWS_KEY'
          - name: AWS_SECRET
            value: 'YOUR_AWS_SECRET'
          - name: REGION
            value: "YOUR_REGION"
        livenessProbe:
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 32Mi
