name: Build Docker Hub Containers

on: [push]

jobs:
  build:
    runs-on: docker://docker:latest
    steps:
    - uses: actions/checkout@v1
    - name: Build AWS ECR Proxy
      run: docker build . --file Dockerfile --tag aws-ecr-proxy:latest
