name: Build Docker Hub Containers 
on: [push]
jobs:
  build-ecr-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish aws-ecr-proxy
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: setkeh/aws-ecr-proxy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        workdir: aws-ecr-proxy
