name: Build Docker Hub Containers 
on: [push]
jobs:
  build-ecr-container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build aws-ecr-proxy/ -t setkeh/aws-ecr-proxy:latest
    - uses: anchore/scan-action@master
      with:
        image-reference: "setkeh/aws-ecr-proxy:latest"
        dockerfile-path: "aws-ecr-proxy/Dockerfile"
        fail-build: true
    - name: anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish Docker Image
      run: docker push setkeh/aws-ecr-proxy:latest
  build-prometheus-alpine:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build aws-ecr-proxy/ -t setkeh/prometheus-alpine:latest
    - uses: anchore/scan-action@master
      with:
        image-reference: "setkeh/prometheus-alpine:latest"
        dockerfile-path: "prometheus-alpine/Dockerfile"
        fail-build: true
    - name: anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish Docker Image
      run: docker push setkeh/prometheus-alpine:latest
#  build-prometheus-alpine:
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@master
#    - name: Publish prometheus-alpine
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: setkeh/prometheus-alpine
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        snapshot: true
#        workdir: prometheus-alpine
#  build-alpine-glibc:
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@master
#    - name: Publish alpine-glibc
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: setkeh/alpine-glibc
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        snapshot: true
#        workdir: alpine-glibc
#  build-archlinux-abs:
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@master
#    - name: Publish archlinux-abs
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: setkeh/archlinux-abs
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        snapshot: true
#        workdir: archlinux-abs
#  build-grafana-alpine:
#    runs-on: self-hosted
#    needs: build-alpine-glibc
#    steps:
#    - uses: actions/checkout@master
#    - name: Publish grafana-alpine
#      uses: elgohr/Publish-Docker-Github-Action@master 
#      with:
#        name: setkeh/grafana-alpine
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        snapshot: true
#        workdir: grafana-alpine
#  build-haproxy-alpine:
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@master
#    - name: Publish haproxy-alpine
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: setkeh/haproxy-alpine
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        snapshot: true
#        workdir: haproxy-alpine
#  build-jdk-8-alpine:
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@master
#    - name: Publish jdk-8-alpine
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: setkeh/jdk-8-alpine
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        snapshot: true
#        workdir: jdk-8-alpine
#  build-jupyter:
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@master
#    - name: Publish jupyter
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: setkeh/jupyter
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        snapshot: true
#        workdir: jupyter
#  build-rundeck-alpine:
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@master
#    - name: Publish rundeck-alpine
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: setkeh/rundeck-alpine
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        snapshot: true
#        workdir: rundeck-alpine
#  build-terraform:
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@master
#    - name: Publish terraform
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: setkeh/terraform
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        snapshot: true
#        workdir: terraform
#