name: Build And Publish ECR Container
on: [push]
jobs:
  build-ecr-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build aws-ecr-proxy/ -t setkeh/aws-ecr-proxy:latest
    - uses: anchore/scan-action@master
      with:
        image-reference: "setkeh/aws-ecr-proxy:latest"
        dockerfile-path: "aws-ecr-proxy/Dockerfile"
        fail-build: true
    - name: anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: ecr-container-failure-reports
        path: ./anchore-reports
    - uses: actions/upload-artifact@v1
      with:
        name: ecr-container-reports
        path: ./anchore-reports
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish Docker Image
      run: docker push setkeh/aws-ecr-proxy:latest